### ISSUE TITLE
Windows10のスタートメニューが一部未翻訳の箇所がある。

### ISSUE THREAD

**Issue by reindex-ot** [creeper-0910/ExplorerPatcher-jp#18]
Windows10のUIに切り替えて使っていたところ、スタートメニューのコンテキストメニューが一部英語の状態でした。
これは仕様なのでしょうか?

![Win10Shell](https://user-images.githubusercontent.com/32851879/184688765-20138147-5b1f-410b-a575-80b78f3e07c7.png)

**Comment by creeper-0910** [comment]
翻訳のし忘れですね....
次期バージョンで対応します、ありがとうございます！

**Comment by creeper-0910** [comment]
失礼しました、どうやら翻訳のミスではなく仕様みたいですね....
