### ISSUE TITLE
pull requestでのエラーについて

### ISSUE THREAD

**Issue by reindex-ot** [creeper-0910/ExplorerPatcher-jp#20]
![Screenshot_2022-08-19-10-44-31-81_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/32851879/185524618-cbe31328-5c16-478c-b5c2-d33a974243dd.jpg)

Artifactの名前に/pull/19/mergeが入っているらしく、/を_に置き換えたりして/が入らないようにしないとダメっぽいです。

**Comment by creeper-0910** [comment]
この問題は[最新のコミット](https://github.com/creeper-0910/ExplorerPatcher-jp/commit/ec214ab1b43883e3d81e44701c06771912176081)で修正されました。
ありがとうございます！
