### ISSUE TITLE
インサイダープレビューの不具合

### ISSUE THREAD

**Issue by merunaaa** [creeper-0910/ExplorerPatcher-jp#32]
windows11のインサイドプレビューでプロパティのスタートメニューのスタイルをwindows10にしてエクスプローラーを再起動するとスタートメニューが開けません。
一部のビルドではタスクバーを右クリックすると強制再起動されます。
対処をお願いします。

**Comment by creeper-0910** [comment]
私はあくまでExplorerPatcherを翻訳している者であり、プログラム自体に修正を加えることはできません。
申し訳ないのですが、本家様の更新をお待ち下さい。

**Comment by creeper-0910** [comment]
返信が無いためcloseします。
再開する場合はこちらのIssueにコメントしてください。
