### ISSUE TITLE
win+Xでショートカットポップアップが表示されない

### ISSUE THREAD

**Issue by KH0000001** [creeper-0910/ExplorerPatcher-jp#34]
Patcher導入前にwin+Xキーで使用できていたショートカットが使えなくなりました。翻訳後の問題ではないっぽいので本家のほうにIssueしにいったほうがいいですかね？

**Comment by KH0000001** [comment]
再起動後、ショートカットがしっかり機能しました。

**Comment by creeper-0910** [comment]
返信が遅くなってしまい申し訳ありません！
ExplorerPatcher-jpの問題ではない場合、本家様のリポジトリにissueを立てていただければと思います。
これからもExplorerPathcer-jpをよろしくお願いいたします！
