### ISSUE TITLE
最新版でdiscord_game_sdk.dllがないエラーが表示される

### ISSUE THREAD

**Issue by reindex-ot** [creeper-0910/ExplorerPatcher-jp#36]
インストーラーを実行するとdiscord_game_sdk.dllがないエラーが出てしまう。

**Comment by creeper-0910** [comment]
以前のバージョンのインストールは正常に動作しますか？

**Comment by reindex-ot** [comment]
以前のバージョンは問題なしで、該当するdllをインストール後に解決はしました。

**Comment by creeper-0910** [comment]
最新版の変更にはdiscord_game_sdkに関わる変更はないように見えます。
お手数をお掛けしますが、本家様のdiscussionに投稿していただけると解決するかもしれません。
