### ISSUE TITLE
UltraUXThemePatcherを適用時に一部機能が反映されない?

### ISSUE THREAD

**Issue by reindex-ot** [creeper-0910/ExplorerPatcher-jp#7]
UltraUXThemePatcher(uxtheme.dll関連のファイルをパッチして非公式なテーマを使用可能にする物)を適用後に一部機能が反映されないようです。例えばエクスプローラーのリボンUI等。
[UltraUxThemePatcher](https://mhoefs.eu/software_uxtheme.php?lang=en)
![サンプル](https://user-images.githubusercontent.com/32851879/170572555-ba5601ad-d0ab-41bb-9a92-cbcbf52259c1.png)

**Comment by creeper-0910** [comment]
それは本家様のExplorerPatcherでも同様に起こる問題でしょうか?
お手数をお掛け致しますが1度試していただき、ExplorerPatcher-jpだけで発生するのかそうでないのかをご報告頂けると幸いです。
よろしくお願い致します。

**Comment by reindex-ot** [comment]
本家でも発生しています。使用したテーマはこちらです。
[Deviantart(ダウンロード時にログイン必須)](https://www.deviantart.com/niivu/art/LIT3-for-Windows-888372946)

**Comment by creeper-0910** [comment]
こちらの環境で試したところUltraUXThemePatcherを適用後、場合によってはアンインストールを実行してもWindows 10 リボンUIなどが機能しなくなるようです(もしくは今回のWindowsアップデートのせいかもしれない)
原因はわからなかったですがあまり併用はしないほうが良さそうですね....お役に立てず申し訳ないです
